import assert from "node:assert/strict";
import test from "node:test";
import { mkdtempSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pbkdf2Sync } from "node:crypto";
import { getPlatformProxy, unstable_dev } from "wrangler";
import { hashToken } from "../lib/credentials.ts";
import { migrationStatements } from '../scripts/migration-statements.mjs';

test("Cloudflare Worker renders and authenticates against isolated D1", { timeout: 180000 }, async () => {
  const directory = mkdtempSync(join(tmpdir(), "aabenbane-worker-"));
  let proxy;
  let worker;
  try {
    proxy = await getPlatformProxy({ configPath: "wrangler.jsonc", persist: { path: join(directory, "v3") } });
    const db = proxy.env.DB;
    for (const file of readdirSync("drizzle").filter(f => f.endsWith(".sql")).sort()) {
      const statements = migrationStatements(readFileSync(join("drizzle", file), "utf8"));
      await db.batch(statements.map(s => db.prepare(s)));
    }
    const salt = Buffer.from("0123456789abcdef0123456789abcdef", "hex");
    const pinHash = salt.toString("hex") + ":" + pbkdf2Sync("987654", salt, 100000, 32, "sha256").toString("hex");
    await db.prepare("INSERT INTO players (member_no,name,email,gender,self_level,role,pin_hash) VALUES (?,?,?,?,?,?,?)")
      .bind("13993","D1 Test Admin","christinsommer@me.com","K","B","admin",pinHash).run();
    await db.prepare("INSERT INTO events (date,registration_opens_at,registration_closes_at,is_test,test_active,registration_override) VALUES (?,?,?,?,?,?) ON CONFLICT(date) DO UPDATE SET is_test=1,test_active=1,registration_override='open'")
      .bind("2026-09-11","2026-09-09T10:00:00Z","2026-09-10T10:00:00Z",1,1,"open").run();
    await db.prepare("INSERT INTO matches (event_id,court,start_time,player_ids,locked) SELECT id,1,'18:00','[1,2,3,4]',1 FROM events WHERE date='2026-09-11'").run();
    await db.prepare("INSERT INTO match_requests (event_id,creator_player_id,invited_member_nos,accepted_player_ids) SELECT id,1,'[\"test-player\",\"someone\",\"another\"]','[1,2]' FROM events WHERE date='2026-09-11'").run();
    await db.prepare("INSERT INTO substitutions (event_id,match_id,outgoing_player_id,replacement_player_id,status) SELECT event_id,id,1,2,'replaced' FROM matches LIMIT 1").run();
    await db.prepare("INSERT INTO feedback (match_id,author_player_id,subject_player_id,balance) SELECT id,1,2,'even' FROM matches LIMIT 1").run();
    const resetToken = "a".repeat(64);
    await db.prepare("INSERT INTO pin_reset_tokens (player_id, token_hash, expires_at) VALUES (?, ?, ?)")
      .bind(1, await hashToken(resetToken), new Date(Date.now() + 60 * 60 * 1000).toISOString())
      .run();
    await proxy.dispose();
    proxy = undefined;

    worker = await unstable_dev(".open-next/worker.js", {
      config: "wrangler.jsonc", local: true, port: 0, persist: true, persistTo: directory,
      vars: { RESEND_API_KEY: "" },
      logLevel: "error", experimental: { disableExperimentalWarning: true, watch: false },
    });
    const page = await worker.fetch("/");
    assert.equal(page.status, 200);
    const health = await worker.fetch('/api/health');
    assert.equal(health.status, 200);
    assert.deepEqual(await health.json(), { ok: true, release: JSON.parse(readFileSync('lib/release-info.json', 'utf8')).id });
    const html=await page.text();
    assert.match(html, /name="codex-preview" content="development"/);
    assert.match(html,/rel="manifest"/);
    assert.match(html,/apple-touch-icon/);
    const manifest=await (await worker.fetch('/manifest.webmanifest')).json();
    assert.equal(manifest.display,'standalone');
    assert.equal(manifest.start_url,'/');
    for(const icon of manifest.icons)assert.equal((await worker.fetch(icon.src)).status,200);
    const anonymous = await worker.fetch("/api/app");
    assert.equal(anonymous.status, 200, await anonymous.clone().text());
    assert.equal((await anonymous.json()).authenticated, false);
    const post = (body, cookie) => worker.fetch("/api/app", {
      method: "POST", headers: { "content-type": "application/json", ...(cookie ? { cookie } : {}) },
      body: JSON.stringify(body),
    });
    const badLogin = await post({ action: "login", memberNo: "13993", pin: "111111" });
    assert.equal(badLogin.status, 401);
    const login = await post({ action: "login", memberNo: "13993", pin: "987654" });
    assert.equal(login.status, 200);
    let cookie = login.headers.get("set-cookie")?.split(";")[0];
    assert.ok(cookie);
    const resetLink = await post({ action: "request_pin_reset", memberNo: "13993" });
    assert.equal(resetLink.status, 502); // Mail is deliberately disabled in this isolated Worker.
    const pinReset = await post({ action: "reset_pin", token: resetToken, pin: "4321", confirmPin: "4321" });
    assert.equal(pinReset.status, 200);
    const loginWithNewPin = await post({ action: "login", memberNo: "13993", pin: "4321" });
    assert.equal(loginWithNewPin.status, 200);
    assert.equal((await (await worker.fetch('/api/app', { headers: { cookie } })).json()).authenticated, false);
    cookie = loginWithNewPin.headers.get("set-cookie")?.split(";")[0];
    assert.ok(cookie);
    const state = await login.json();
    assert.equal(state.calendarDates.length,34);
    assert.equal((await post({action:'add_date',date:'2099-05-04'},cookie)).status,200);
    assert.equal((await post({action:'add_date',date:'2099-05-04'},cookie)).status,409);
    assert.equal((await post({action:'add_date',date:'2027-02-30'},cookie)).status,400);
    assert.equal((await post({action:'remove_date',eventId:state.event.id},cookie)).status,409);
    assert.equal(state.user.role, "admin");
    assert.equal(state.user.christinRanking,null);
    assert.equal((await post({action:'delete_member',playerId:state.user.id,confirmMemberNo:'13993'},cookie)).status,400);
    assert.equal(state.user.memberNo, "13993");
    assert.equal(state.user.pinHash, undefined);
    assert.equal(state.players.length, 1);
    assert.equal(state.signup.nHours,0);
    assert.equal(state.signup.status,'not_registered');
    assert.equal(state.signups.length,1);
    assert.equal(state.signups[0].signup.nHours,0);
    assert.equal(state.event.date,"2026-09-11");
    assert.equal(state.event.testActive,true);
    assert.equal(state.isOpen,true);
    const current = await worker.fetch("/api/app", { headers: { cookie } });
    assert.equal((await current.json()).user.role, "admin");
    const registration = await post({ action: "register", memberNo: "test-player", pin: "123456", firstName: "D1", lastName: "Player", email: "player@example.com", gender: "M", level: "B", christinRanking:9, role:"admin" });
    assert.equal(registration.status, 200);
    const registered=await registration.json();
    assert.equal(registered.user.role,"player");
    assert.equal(registered.user.firstName,"D1");
    assert.equal(registered.user.lastName,"Player");
    assert.deepEqual(registered.signup.szPossible,[]);
    assert.equal(registered.signup.nPossible,0);
    assert.equal(registered.signup.nHours,0);
    assert.equal('christinRanking' in registered.user,false);
    const playerCookie = registration.headers.get("set-cookie")?.split(";")[0];
    assert.equal((await post({action:'delete_member',playerId:state.user.id,confirmMemberNo:'13993'},playerCookie)).status,403);
    assert.equal((await post({action:'add_date',date:'2099-06-01'},playerCookie)).status,403);
    assert.equal((await post({action:'remove_date',eventId:state.event.id},playerCookie)).status,403);
    const forbidden = await post({ action: "set_admin", playerId: 1, makeAdmin: true }, playerCookie);
    assert.equal(forbidden.status, 403);
    const profile=await post({action:"update_profile",firstName:"Updated",lastName:"Player",email:"updated@example.com",level:"AB",memberNo:"13993",playerId:1,role:"admin",christinRanking:9},playerCookie);
    assert.equal(profile.status,200);
    const updated=await profile.json();
    assert.equal(updated.user.name,"Updated Player");
    assert.equal(updated.user.memberNo,"test-player");
    assert.equal(updated.user.email,"updated@example.com");
    assert.equal(updated.user.selfLevel,"AB");
    const initialRankingState=await (await worker.fetch('/api/app',{headers:{cookie}})).json();
    assert.equal(initialRankingState.players.find(p=>p.id===updated.user.id).christinRanking,5);
    assert.equal(updated.user.role,"player");
    assert.equal(updated.user.gender,"M");
    const genderProfile={action:'update_profile',firstName:'Updated',lastName:'Player',email:'updated@example.com',level:'AB',gender:'K'};
    assert.equal((await (await post(genderProfile,playerCookie)).json()).user.gender,'K');
    assert.equal((await post({...genderProfile,gender:'X'},playerCookie)).status,400);
    assert.equal((await post({...genderProfile,gender:null},playerCookie)).status,400);
    assert.equal('christinRanking' in updated.user,false);
    assert.equal((await post({action:"update_profile",firstName:"",lastName:"Player",email:"bad",level:"B"},playerCookie)).status,400);
    assert.equal((await post({action:"set_cr",playerId:updated.user.id,christinRanking:8},playerCookie)).status,403);
    for(const cr of [0,10,1.5,"5"])assert.equal((await post({action:"set_cr",playerId:updated.user.id,christinRanking:cr},cookie)).status,400);
    assert.equal((await post({action:"set_cr",playerId:updated.user.id,christinRanking:8},cookie)).status,200);
    const memberState=await (await worker.fetch('/api/app',{headers:{cookie:playerCookie}})).json();
    assert.equal(JSON.stringify(memberState).includes('christinRanking'),false);
    const adminState=await (await worker.fetch('/api/app',{headers:{cookie}})).json();
    assert.equal(adminState.players.find(p=>p.id===updated.user.id).christinRanking,8);
    const editMember={action:'update_member',playerId:updated.user.id,memberNo:'must-not-change',firstName:'Admin Edited',lastName:'Member',email:'edited@example.com',gender:'M',phone:'12345678',level:'BC',christinRanking:7,role:'admin',pin:'999999'};
    assert.equal((await post(editMember,playerCookie)).status,403);
    assert.equal((await post({...editMember,christinRanking:10},cookie)).status,400);
    assert.equal((await post({...editMember,level:'b niveau'},cookie)).status,400);
    assert.equal((await post({...genderProfile,level:'B+'},playerCookie)).status,400);
    const edited=await (await post(editMember,cookie)).json();
    const editedPlayer=edited.players.find(p=>p.id===updated.user.id);
    assert.equal(editedPlayer.memberNo,'test-player');
    assert.equal(editedPlayer.firstName,'Admin Edited');
    assert.equal(editedPlayer.email,'edited@example.com');
    assert.equal(editedPlayer.phone,'12345678');
    assert.equal(editedPlayer.selfLevel,'BC');
    assert.equal(editedPlayer.christinRanking,7);
    assert.equal(editedPlayer.role,'player');
    assert.equal((await post({action:'login',memberNo:'test-player',pin:'123456'})).status,200);
    assert.equal((await post({action:"set_cr",playerId:updated.user.id,christinRanking:null},cookie)).status,200);
    assert.equal((await post({action:"set_registration",mode:"closed"},playerCookie)).status,403);
    assert.equal((await post({action:"end_test"},playerCookie)).status,403);
    assert.equal((await post({action:'signup',availability:['18:00'],requestedHours:1},playerCookie)).status,400);
    assert.equal((await post({action:'signup',availability:['18:00','18:30'],requestedHours:2},playerCookie)).status,400);
    const signupBody={action:"signup",availability:["18:00","19:00"],requestedHours:1};
    const example={action:'signup',nHours:2,nPossible:3,szPossible:['18:30','19:30','20:30']};
    const saved=await (await post(example,playerCookie)).json();
    assert.equal(saved.signup.nHours,2);
    assert.ok(Number.isInteger(saved.signup.signupOrder) && saved.signup.signupOrder > 0);
    assert.equal((await post({action:'set_signup_status',signupId:saved.signup.id,status:'waitlist'},playerCookie)).status,403);
    assert.equal((await post({action:'set_signup_status',signupId:saved.signup.id,status:'invalid'},cookie)).status,400);
    assert.equal((await post({action:'set_signup_status',signupId:null,status:'active'},cookie)).status,400);
    const statusChanged = await post({action:'set_signup_status',signupId:saved.signup.id,status:'waitlist'},cookie);
    assert.equal(statusChanged.status,200);
    const changedSignup = (await statusChanged.json()).signups.find(row=>row.signup.id===saved.signup.id).signup;
    assert.equal(changedSignup.status,'waitlist');
    assert.equal(changedSignup.signupOrder,saved.signup.signupOrder);
    assert.equal(changedSignup.nHours,saved.signup.nHours);
    assert.deepEqual((await (await worker.fetch('/api/app',{headers:{cookie:playerCookie}})).json()).registeredMembers,[]);
    assert.equal((await post({action:'set_signup_status',signupId:saved.signup.id,status:'active'},cookie)).status,200);
    const editedSignup = await (await post({...example,nHours:3,signupOrder:-100},playerCookie)).json();
    assert.equal(editedSignup.signup.signupOrder,saved.signup.signupOrder);
    await post(example,playerCookie);
    assert.equal(saved.signup.nPossible,3);
    assert.deepEqual(saved.signup.szPossible,example.szPossible);
    const roster=await (await worker.fetch('/api/app',{headers:{cookie}})).json();
    assert.equal(roster.signups.length,2);
    assert.equal(roster.signups.find(row=>row.player.memberNo==='13993').signup.nHours,0);
    assert.equal(roster.signups.find(row=>row.player.memberNo==='test-player').signup.nHours,2);
    assert.equal(roster.signups[0].signup.signupOrder,saved.signup.signupOrder);
    const publicRoster = await (await worker.fetch('/api/app',{headers:{cookie:playerCookie}})).json();
    assert.deepEqual(publicRoster.registeredMembers,[{id:updated.user.id,name:'Admin Edited Member'}]);
    assert.deepEqual(roster.registeredMembers,publicRoster.registeredMembers);
    assert.deepEqual(publicRoster.players,[]);
    const cancelled=await (await post({action:'cancel_signup'},playerCookie)).json();
    assert.equal(cancelled.signup.nHours,0);
    assert.equal(cancelled.signup.status,'cancelled');
    assert.deepEqual(cancelled.registeredMembers,[]);
    assert.deepEqual(cancelled.signup.szPossible,[]);
    assert.equal(cancelled.signup.availability,'[]');
    const cancelledRoster=await (await worker.fetch('/api/app',{headers:{cookie}})).json();
    assert.equal(cancelledRoster.signups.find(row=>row.player.memberNo==='test-player').signup.nHours,0);
    assert.equal((await post({...example,nPossible:2},playerCookie)).status,400);
    assert.equal((await post({...example,nHours:4},playerCookie)).status,400);
    const rejoined = await (await post({...example,nHours:3},playerCookie)).json();
    assert.equal(rejoined.signup.nHours,3);
    assert.ok(rejoined.signup.signupOrder > saved.signup.signupOrder);
    assert.equal((await (await post({...example,nHours:0,nPossible:0,szPossible:[]},playerCookie)).json()).signup.nHours,0);
    const legacyGenerate = await post({action:'generate'},cookie);
    assert.equal(legacyGenerate.status,400);
    assert.match((await legacyGenerate.json()).error,/Algoritme foreslå kampe/);
    const optimizerRequest = headers => worker.fetch('/api/optimizer', {method:'POST', headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({action:'solve',eventId:state.event.id,weights:{}})});
    assert.equal((await optimizerRequest({})).status,401);
    assert.equal((await optimizerRequest({cookie:playerCookie})).status,403);
    const optedOut=await (await worker.fetch('/api/app',{headers:{cookie:playerCookie}})).json();
    assert.equal(optedOut.signup.status,'active');
    assert.equal(optedOut.signup.nHours,0);
    assert.deepEqual(optedOut.registeredMembers,[]);
    assert.deepEqual(optedOut.matches,[]);
    assert.equal((await post(signupBody,playerCookie)).status,200);
    assert.equal((await post({action:"set_registration",mode:"closed"},cookie)).status,200);
    assert.equal((await post(signupBody,playerCookie)).status,400);
    assert.equal((await post(signupBody,cookie)).status,400);
    assert.equal((await post({action:"cancel_signup"},playerCookie)).status,400);
    assert.equal((await post({action:"request_match",memberNos:["a","b","c"]},playerCookie)).status,400);
    const auto=await post({action:"set_registration",mode:"auto"},cookie);
    assert.equal((await auto.json()).event.registrationOverride,"auto");
    const open=await post({action:"set_registration",mode:"open"},cookie);
    assert.equal((await open.json()).isOpen,true);
    assert.equal((await post(signupBody,playerCookie)).status,200);
    assert.equal((await post({action:"set_registration",mode:"invalid"},cookie)).status,400);
    const end=await post({action:"end_test"},cookie);
    assert.equal(end.status,200);
    const ended=await end.json();
    assert.equal(ended.event.testActive,false);
    assert.notEqual(ended.event.id,state.event.id);
    for (const date of ended.calendarDates) {
      assert.equal((await post({action:'remove_date',eventId:date.id},cookie)).status,200);
    }
    const empty=await (await worker.fetch('/api/app',{headers:{cookie}})).json();
    assert.equal(empty.event,null);
    assert.deepEqual(empty.calendarDates,[]);
    const emptyMember=await (await worker.fetch('/api/app',{headers:{cookie:playerCookie}})).json();
    assert.equal('christinRanking' in emptyMember.user,false);
    assert.equal((await post({action:'update_profile',firstName:'Updated',lastName:'Player',email:'updated@example.com',level:'AB'},playerCookie)).status,200);
    const restored=await (await post({action:'add_date',date:'2026-09-11'},cookie)).json();
    assert.equal(restored.calendarDates[0].id,state.event.id);
    const future=await (await post({action:'add_date',date:'2099-05-04'},cookie)).json();
    assert.equal(future.event.date,'2099-05-04');
    const imported = [{ A: '18:30', B: '19:30', C: '1', D: 'Christin Hytoft Sommer', E: 'Søren Schødt', F: 'Maiken Pelby', G: 'Glen Hytoft Sommer' }];
    assert.equal((await post({action:'import_kampplan',schedule:imported},playerCookie)).status,403);
    const importedResponse = await post({action:'import_kampplan',schedule:imported},cookie);
    assert.equal(importedResponse.status,200);
    assert.deepEqual((await importedResponse.json()).importedMatches,imported);
    assert.deepEqual((await (await worker.fetch('/api/app',{headers:{cookie}})).json()).importedMatches,imported);
    const privateDraft = await (await worker.fetch('/api/app')).json();
    assert.deepEqual(privateDraft.importedMatches,[]);
    assert.equal(privateDraft.event.importedKampplan,'');
    assert.equal((await post({action:'remove_kampplan'},playerCookie)).status,403);
    assert.equal((await post({action:'set_optimizer_defaults',weights:{FactorSingle:22}},playerCookie)).status,403);
    assert.equal((await post({action:'set_optimizer_defaults',weights:{FactorSingle:1.5}},cookie)).status,400);
    const savedDefaults = await post({action:'set_optimizer_defaults',weights:{FactorSingle:22,FactorDoubleSameSex:8,Factor3OfAKind:44}},cookie);
    assert.equal(savedDefaults.status,200);
    assert.equal((await savedDefaults.json()).optimizerDefaults.FactorSingle,22);
    const reloadedDefaults = await (await worker.fetch('/api/app',{headers:{cookie}})).json();
    assert.equal(reloadedDefaults.optimizerDefaults.FactorDoubleSameSex,8);
    assert.equal(reloadedDefaults.optimizerDefaults.Factor3OfAKind,44);
    assert.equal((await post({action:'remove_kampplan',eventId:-1},cookie)).status,409);

    assert.equal((await post({action:'publish'},cookie)).status,200);
    assert.deepEqual((await (await worker.fetch('/api/app')).json()).importedMatches,imported);
    const clearedResponse = await post({action:'remove_kampplan'},cookie);
    assert.equal(clearedResponse.status,200);
    const cleared = await clearedResponse.json();
    assert.equal(cleared.optimizerWeights.FactorSingle,22);
    assert.deepEqual(cleared.importedMatches,[]);
    assert.deepEqual(cleared.adminMatches,[]);
    assert.equal(cleared.event.status,'draft');
    assert.equal(cleared.event.publishedAt,null);
    assert.ok(cleared.signupHistory.length > 0);
    for(const level of ['B+','A-','ukendt','a ukendt','']) {
      assert.equal((await post({action:'register',memberNo:'invalid-ranking-'+level,pin:'123456',firstName:'Ranking',lastName:'Test',email:'ranking@example.com',gender:'K',level})).status,400);
    }
    for(const [level,cr] of Object.entries({A:2,AB:4,B:5,BC:7,C:8,Begynder:9})) {
      const newMember=await post({action:'register',memberNo:'ranking-'+level,pin:'123456',firstName:'Ranking',lastName:'Test',email:'ranking@example.com',gender:'K',level,christinRanking:1});
      assert.equal(newMember.status,200);
      const newState=await newMember.json();
      assert.equal(newState.user.selfLevel,level);
      assert.equal('christinRanking' in newState.user,false);
      const adminRankingState=await (await worker.fetch('/api/app',{headers:{cookie}})).json();
      assert.equal(adminRankingState.players.find(p=>p.id===newState.user.id).christinRanking,cr);
    }
    assert.equal((await post({action:'delete_member',playerId:updated.user.id,confirmMemberNo:'wrong'},cookie)).status,400);
    const deletion=await post({action:'delete_member',playerId:updated.user.id,confirmMemberNo:'test-player'},cookie);
    assert.equal(deletion.status,200);
    const afterDelete=await deletion.json();
    assert.equal(afterDelete.players.some(p=>p.id===updated.user.id),false);
    assert.equal(afterDelete.signupHistory.some(row=>row.player.id===updated.user.id),false);
    assert.equal((await (await worker.fetch('/api/app',{headers:{cookie:playerCookie}})).json()).authenticated,false);
    assert.equal((await post({action:'login',memberNo:'test-player',pin:'123456'})).status,401);
    assert.equal((await post({action:'delete_member',playerId:updated.user.id,confirmMemberNo:'test-player'},cookie)).status,404);
    const logout = await post({ action: "logout" }, cookie);
    assert.equal(logout.status, 200);
    const loggedOut = await worker.fetch("/api/app", { headers: { cookie } });
    assert.equal((await loggedOut.json()).authenticated, false);
    await worker.stop(); worker=undefined;
    proxy=await getPlatformProxy({configPath:'wrangler.jsonc',persist:{path:join(directory,'v3')}});
    assert.equal((await proxy.env.DB.prepare('SELECT count(*) AS n FROM sessions WHERE player_id=?').bind(updated.user.id).first()).n,0);
    assert.equal((await proxy.env.DB.prepare('SELECT count(*) AS n FROM signups WHERE player_id=?').bind(updated.user.id).first()).n,0);
    assert.equal((await proxy.env.DB.prepare('SELECT count(*) AS n FROM match_requests').first()).n,0);
    assert.equal((await proxy.env.DB.prepare('SELECT count(*) AS n FROM feedback').first()).n,0);
    assert.equal((await proxy.env.DB.prepare('SELECT count(*) AS n FROM matches').first()).n,1);
    const replacement=await proxy.env.DB.prepare('SELECT replacement_player_id,status FROM substitutions LIMIT 1').first();
    assert.equal(replacement.replacement_player_id,null);
    assert.equal(replacement.status,'unresolved');
  } finally {
    await worker?.stop();
    await proxy?.dispose();
    rmSync(directory, { recursive: true, force: true });
  }
});
